global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:4000"]

  - job_name: "server1-fastapi"
    static_configs:
      - targets: ["fastapi-server:5001"]

  - job_name: "server2-flask"
    static_configs:
      - targets: ["flask-server:5002"]

  - job_name: "server3-deno"
    static_configs:
      - targets: ["deno-server:5003"]
